"""Render typed, ego-only VQA sidecar samples for make_kong A/B layouts.

For each selected variant-A or variant-B layout and target group, the
collector holds the robots at home, renders clean ``cam_head`` images of the
opponent discard knocked face-up, and emits five question families:

- ``discard_suit`` (only on the zero-fallen scene): which of the five
  canonical suits the pushed-down opponent tile shows;
- ``fallen_tile_count``: how many own-side row tiles are down (0-5);
- ``fallen_tile_indices``: the 1-based left-to-right indices of every fallen
  row tile, ``none`` when empty;
- ``missing_matching_tile_bboxes``: visible boxes of matching tiles that
  should still be knocked down, ``none`` when empty;
- ``wrong_fallen_tile_bboxes``: visible boxes of incorrectly fallen
  non-matching tiles, ``none`` when empty.

Example:
    python vqa_gen/make_kong/generate_make_kong_vqa.py \
        --headless --enable_cameras --device-id 0 --seed 0 \
        --variant a,b --layout-ids 0 --max-layouts 1 \
        --output-dir ./output/RoboDojo_vqa_v2/make_kong_ab_seed0 --overwrite
"""

import argparse
from copy import deepcopy
import json
import logging
from pathlib import Path
import random
import sys
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
# RoboDojo must precede XPolicyLab: both have a top-level ``utils`` package.
for package_root in (REPO_ROOT / "XPolicyLab", REPO_ROOT):
    if str(package_root) not in sys.path:
        sys.path.insert(0, str(package_root))

from isaaclab.app import AppLauncher

from vqa_gen.make_kong.generate_layouts import DEFAULT_OUTPUT_DIR, VARIANTS, load_vqa_layout_pool
from vqa_gen.make_kong.scene_plan import FallenCase, plan_cases
from vqa_gen.make_kong.tile_faces import FACE_NAMES, face_of_category
from vqa_gen.vqa.sidecar import (
    SidecarWriter,
    VisibilityThresholds,
    base_record,
    bbox_from_mask,
    classify_mask_visibility,
    json_dumps,
)

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--device-id", type=int, default=0)
parser.add_argument("--seed", type=int, default=2810, help="Seed for deterministic case sampling and scene ids.")
parser.add_argument(
    "--variant",
    default="a,b",
    help='Comma-separated layout variants to render, e.g. "a" or "a,b" (default: a,b).',
)
parser.add_argument(
    "--layout-ids",
    default="all",
    help="Comma-separated A/B layout IDs, e.g. 0,1,2, or \"all\" for every pair in the pool.",
)
parser.add_argument("--max-layouts", type=int, default=None, help="Optional debug cap after expanding --layout-ids.")
parser.add_argument("--fps", type=int, default=25, help="Camera capture frequency.")
parser.add_argument(
    "--target-groups",
    default="0,1,2,3",
    help="Comma-separated discard indices (0-3) whose matching group is the target.",
)
parser.add_argument(
    "--layout-root",
    type=Path,
    default=DEFAULT_OUTPUT_DIR,
    help="Directory containing the make_kong A/B layout pool generated by generate_layouts.py.",
)
parser.add_argument(
    "--output-dir",
    type=Path,
    default=Path("data/RoboDojo_vqa_v2/make_kong_ab"),
    help="Output directory for the typed VQA sidecar.",
)
parser.add_argument("--overwrite", action="store_true", help="Replace --output-dir if it already exists.")
AppLauncher.add_app_launcher_args(parser)
ARGS = parser.parse_args()

app_launcher = AppLauncher(ARGS)
simulation_app = app_launcher.app

import numpy as np
from omegaconf import OmegaConf
from PIL import Image
import torch

from env.global_configs import BENCHMARK, ENV_CONFIG_PATH, ROOT_DIR
from env.observation_manager.obs_manager import ObsManager
from task.RoboDojo import task_registry
from utils.load_file import load_yaml
from utils.pipeline_utils import process_config, process_randomization

# Robot-side tiles are pushed away from the robot and rotate onto the table.
# The opponent discard moves toward the robot and turns face-up first, which is
# the sole visual reference for deciding the matching robot-side tile group.
ROBOT_SIDE_FALLEN_QUATERNION = np.asarray([1.0, 0.0, 0.0, 0.0], dtype=np.float32)
REFERENCE_TILE_FALLEN_QUATERNION = np.asarray([0.0, 0.0, 0.0, 1.0], dtype=np.float32)
ROBOT_SIDE_PUSH_DIRECTION = np.asarray([0.0, 1.0, 0.0], dtype=np.float32)
REFERENCE_TILE_PUSH_DIRECTION = np.asarray([0.0, -1.0, 0.0], dtype=np.float32)
FALLEN_FORWARD_OFFSET_M = 0.045
FALLEN_Z_OFFSET_M = -0.016
KONG_GROUPS = (
    ("mahjong0_0", "mahjong0_1", "mahjong0_2"),
    ("mahjong1_0", "mahjong1_1", "mahjong1_2"),
    ("mahjong2_0", "mahjong2_1", "mahjong2_2"),
    ("mahjong3_0", "mahjong3_1", "mahjong3_2"),
)
DISTRACTOR_ROBOT_SIDE_GROUP = ("mahjong4_0", "mahjong4_1")
DISCARD_LABELS = ("mahjong5_0", "mahjong6_0", "mahjong7_0", "mahjong8_0")
TILE_VISIBILITY = VisibilityThresholds(32, 4, 0.05, 0.5)
RENDER_STABILIZATION_FRAMES = 12
LOGGER = logging.getLogger("make_kong_vqa_ab")


def _configure_logging() -> None:
    """Keep collector progress while suppressing verbose dependencies."""

    if not LOGGER.handlers:
        handler = logging.StreamHandler()
        handler.setFormatter(logging.Formatter("[%(name)s] %(message)s"))
        LOGGER.addHandler(handler)
    LOGGER.setLevel(logging.INFO)
    LOGGER.propagate = False
    for dependency in ("curobo", "matplotlib", "PIL"):
        logging.getLogger(dependency).setLevel(logging.WARNING)


def _parse_int_csv(value: str, *, valid: set[int] | None = None, flag: str) -> list[int]:
    result = [int(item.strip()) for item in value.split(",") if item.strip()]
    if not result:
        raise ValueError(f"{flag} must contain at least one integer.")
    if valid is not None:
        invalid = [item for item in result if item not in valid]
        if invalid:
            raise ValueError(f"{flag} contains invalid values {invalid}; expected values in {sorted(valid)}.")
    return result


def _parse_layout_ids(value: str, pool: dict[tuple[str, int], Any]) -> list[int]:
    available = sorted({layout_id for _, layout_id in pool})
    if value.strip().lower() == "all":
        layout_ids = available
    else:
        layout_ids = _parse_int_csv(value, flag="--layout-ids")
        unknown = [layout_id for layout_id in layout_ids if layout_id not in available]
        if unknown:
            raise ValueError(f"--layout-ids contains unknown A/B layout IDs {unknown}.")
    if ARGS.max_layouts is not None:
        if ARGS.max_layouts <= 0:
            raise ValueError("--max-layouts must be positive.")
        layout_ids = layout_ids[: ARGS.max_layouts]
    if not layout_ids:
        raise ValueError("No layout IDs selected.")
    return layout_ids


def _as_numpy(value: Any, *, dtype=None) -> np.ndarray:
    if isinstance(value, torch.Tensor):
        value = value.detach().cpu().numpy()
    return np.asarray(value, dtype=dtype)


def _build_env_config(device_id: int, seed: int):
    task_name = "make_kong"
    eval_config = load_yaml(Path(ENV_CONFIG_PATH) / "arx_x5.yml")
    eval_config.update(
        {
            "task_name": task_name,
            "num_envs": 1,
            "device_id": device_id,
            "eval_batch": False,
            "policy_name": "vqa_renderer",
            "additional_info": "static_fallen_tile_vqa_ab",
            "seed": seed,
        }
    )
    task_config_path = task_registry.task_config_path(Path(ROOT_DIR) / "task" / BENCHMARK / "config", task_name)
    config = OmegaConf.create(
        {
            "sim": load_yaml(Path(ENV_CONFIG_PATH) / "sim" / f"{eval_config['config']['sim']}.yml"),
            "scene": load_yaml(Path(ENV_CONFIG_PATH) / "scene" / f"{eval_config['config']['scene']}.yml"),
            "camera": load_yaml(Path(ENV_CONFIG_PATH) / "camera" / f"{eval_config['config']['camera']}.yml"),
            "robot": load_yaml(Path(ENV_CONFIG_PATH) / "robot" / f"{eval_config['config']['robot']}.yml"),
            "task_env": load_yaml(task_config_path),
            "eval_cfg": eval_config,
            "deploy_cfg": {},
        }
    )
    config.sim.scene.num_envs = 1
    config.eval_cfg.num_envs = 1
    config.sim.device = f"cuda:{device_id}"
    config.sim.seed = [0]
    config.sim.render = {
        "rendering_mode": "quality",
        "antialiasing_mode": "DLAA",
        "enable_dl_denoiser": True,
        "samples_per_pixel": 1024,
    }
    config = process_randomization(config)
    config, _ = process_config(config, task_name=task_name)
    for robot_cfg in config.robot.robots:
        robot_cfg["need_planner"] = False
    config.camera.default_frequency = ARGS.fps
    config.camera.annotator = {
        "common": {"enabled": False},
        "cam_head": {
            "enabled": True,
            "rgb_capture": {"type": "rgb", "device": "cpu"},
            "depth_capture": {"type": "distance_to_image_plane", "device": "cpu"},
            "instance_capture": {"type": "instance_segmentation_fast", "device": "cpu"},
        },
    }
    return config


def _create_env(config):
    _, task_class = task_registry.load_task_class("make_kong")
    env = task_class(config, simulation_app)
    env.eval_cfg = config.eval_cfg
    env.scene_manager.layout_manager.replay = True

    obs_manager = ObsManager(
        obs_config=deepcopy(config.eval_cfg.get("observation", {})),
        num_envs=env.num_envs,
        dt=env.dt,
        task_name="make_kong",
        description_cfg=config.eval_cfg.get("description", {}),
        seeds_per_env=env.env_seed_list,
    )
    original_post_setup_scene = env._post_setup_scene

    def post_setup_scene(sim) -> None:
        original_post_setup_scene(sim)
        obs_manager.initialize(env)

    env._post_setup_scene = post_setup_scene
    env.obs_manager = obs_manager
    env.interact = False
    env.step_lim = 100000
    return env


def _reset_layout(env, layout_id: int, scene_layout: dict[str, Any]) -> None:
    env.scene_manager.layout_manager.set_saved_layout(0, deepcopy(scene_layout))
    env.reset(seed=[layout_id])
    _ensure_layout_scene_objects(env)
    env.scene_manager.apply_saved_poses(env_idx_list=[0])
    for _ in range(10):
        env.render()
    for _ in range(80):
        env.sim_step(render=False)
    env.obs_manager.reset()
    _restore_robot_home(env)


def _scene_object_exists(env, label: str) -> bool:
    layout = env.scene_manager.layout_manager
    instance_name = layout.get_instance_name(env_idx=0, label=label)
    if instance_name is None:
        return False
    instance_type = layout.instance_type_by_env[0].get(instance_name)
    if instance_type is None:
        return False
    key = f"env0_{instance_type}_{instance_name}"
    objects = env.scene_manager.get_objects(env_ids=[0], object_name=instance_name, object_type=instance_type)
    return objects.get(key) is not None


def _ensure_layout_scene_objects(env) -> None:
    missing_labels = [label for label in _tile_labels() if not _scene_object_exists(env, label)]
    if missing_labels:
        raise RuntimeError(
            "Scene objects are missing after creating a fresh layout environment: "
            f"{missing_labels}. The selected layout likely lacks required make_kong labels."
        )


def _restore_robot_home(env) -> None:
    """Teleport target robots home with zero velocity for a static snapshot."""

    env.robot_manager.reset()
    for robot, key in zip(env.robot_manager.robot_list, env.robot_manager.robot_key, strict=True):
        if robot.type != "target":
            continue
        default_joint_pos = key.data.default_joint_pos.clone()
        zero_joint_vel = torch.zeros_like(key.data.default_joint_vel)
        key.write_joint_state_to_sim(default_joint_pos, zero_joint_vel)
        key.set_joint_position_target(default_joint_pos)
    env.sim_step(render=False)
    env.robot_manager.set_robot_init_pose()
    env.robot_manager.set_robot_init_state()


def _label_object(env, label: str):
    layout = env.scene_manager.layout_manager
    instance_name = layout.get_instance_name(env_idx=0, label=label)
    if instance_name is None:
        raise RuntimeError(f"No scene instance for label {label!r}")
    obj = layout.get_scene_object(env_idx=0, inst_name=instance_name)
    if obj is None:
        raise RuntimeError(f"No scene object for label {label!r} (instance {instance_name!r})")
    position, orientation = layout.get_instance_pose(env_idx=0, inst_name=instance_name)
    return obj, _as_numpy(position, dtype=np.float32), _as_numpy(orientation, dtype=np.float32)


def _set_label_pose(env, label: str, position: np.ndarray, orientation: np.ndarray) -> None:
    obj, _, _ = _label_object(env, label)
    obj.set_local_pose(
        translation=np.asarray(position, dtype=np.float32), orientation=np.asarray(orientation, dtype=np.float32)
    )
    if hasattr(obj, "set_velocities"):
        obj.set_velocities(np.zeros((1, 6), dtype=np.float32))


def _row_labels() -> tuple[str, ...]:
    """Return the 14 robot-side row tiles (kong groups plus support pair)."""

    return tuple(label for group in KONG_GROUPS for label in group) + DISTRACTOR_ROBOT_SIDE_GROUP


def _tile_labels() -> tuple[str, ...]:
    return tuple(list(_row_labels()) + list(DISCARD_LABELS) + ["mahjong9_0"])


def _snapshot_tile_poses(env) -> dict[str, tuple[np.ndarray, np.ndarray]]:
    return {
        label: (position.copy(), orientation.copy())
        for label in _tile_labels()
        for _, position, orientation in [_label_object(env, label)]
    }


def _restore_tile_poses(env, poses: dict[str, tuple[np.ndarray, np.ndarray]]) -> None:
    for label, (position, orientation) in poses.items():
        _set_label_pose(env, label, position, orientation)


def _settle(env, *, sim_steps: int = 20) -> None:
    for _ in range(sim_steps):
        env.sim_step(render=False)
    env.obs_manager.reset()


class AnnotationMappingError(RuntimeError):
    """The renderer could not establish an unambiguous instance mask."""


def _capture_ego_annotations(env) -> tuple[np.ndarray, np.ndarray, np.ndarray, dict[str, Any]]:
    captured = env.capture_manager.step(env_ids=[0])
    camera_names = env.camera_manager.camera_names[0]
    if "cam_head" not in camera_names:
        raise AnnotationMappingError(f"cam_head is unavailable; cameras={camera_names}")
    data = captured[camera_names.index("cam_head")]
    required = {"rgb", "distance_to_image_plane", "instance_segmentation_fast"}
    missing = required.difference(data)
    if missing:
        raise AnnotationMappingError(f"missing annotation buffers: {sorted(missing)}")
    rgb = np.asarray(data["rgb"][0]["data"], dtype=np.uint8)[..., :3]
    depth = np.asarray(data["distance_to_image_plane"][0]["data"], dtype=np.float32).squeeze(-1)
    instance = np.asarray(data["instance_segmentation_fast"][0]["data"]).squeeze(-1)
    return rgb, depth, instance, data["instance_segmentation_fast"][0].get("info", {})


def _reset_ego_render_product(env) -> None:
    """Discard tiled-camera DLAA history after a static-scene teleport."""

    import omni.usd

    camera_names = env.camera_manager.camera_names[0]
    if "cam_head" not in camera_names:
        raise AnnotationMappingError(f"cam_head is unavailable; cameras={camera_names}")
    omni.usd.get_context().reset_renderer_accumulation()
    env.capture_manager.recreate_render_products([camera_names.index("cam_head")])
    for _ in range(RENDER_STABILIZATION_FRAMES):
        env.render()


def _set_semantic_label(entity: Any, semantic_label: str) -> str:
    from isaacsim.core.utils.semantics import add_labels, remove_labels
    import omni.usd

    prim = getattr(entity, "prim", None)
    if prim is None:
        prim_path = getattr(entity, "prim_path", None)
        prim = omni.usd.get_context().get_stage().GetPrimAtPath(str(prim_path)) if prim_path else None
    if not prim or not prim.IsValid():
        raise AnnotationMappingError(f"invalid prim for {semantic_label!r}")
    remove_labels(prim, include_descendants=True)
    add_labels(prim, [semantic_label])
    return str(prim.GetPath())


def _label_matches(value: Any, semantic_label: str) -> bool:
    if isinstance(value, dict):
        return any(_label_matches(item, semantic_label) for item in value.values())
    if isinstance(value, (list, tuple, set)):
        return any(_label_matches(item, semantic_label) for item in value)
    text = str(value)
    return text == semantic_label or (not text.startswith("/") and semantic_label in text)


def _prim_path_matches(value: Any, prim_path: str) -> bool:
    """Match an instance identity path exactly, never by a shared prefix."""

    if isinstance(value, dict):
        return any(_prim_path_matches(item, prim_path) for item in value.values())
    if isinstance(value, (list, tuple, set)):
        return any(_prim_path_matches(item, prim_path) for item in value)
    return str(value) == prim_path


def _renderer_identity_matches(value: Any, semantic_label: str, prim_path: str) -> bool:
    return _label_matches(value, semantic_label) or _prim_path_matches(value, prim_path)


def _semantic_id_map(
    info: dict[str, Any], semantic_labels: dict[str, str], semantic_prim_paths: dict[str, str]
) -> dict[str, list[int]]:
    labels = info.get("idToLabels") or info.get("id_to_labels") or info.get("labels")
    if not isinstance(labels, dict):
        raise AnnotationMappingError("instance segmentation did not provide idToLabels")
    return {
        label: [
            int(key)
            for key, value in labels.items()
            if _renderer_identity_matches(value, semantic_label, semantic_prim_paths[label])
        ]
        for label, semantic_label in semantic_labels.items()
    }


def _mask_for_semantic(
    instance: np.ndarray,
    info: dict[str, Any],
    semantic_label: str,
    prim_path: str,
) -> np.ndarray:
    labels = info.get("idToLabels") or info.get("id_to_labels") or info.get("labels")
    if not isinstance(labels, dict):
        raise AnnotationMappingError("instance segmentation did not provide idToLabels")
    ids = [int(key) for key, value in labels.items() if _renderer_identity_matches(value, semantic_label, prim_path)]
    if len(ids) != 1:
        raise AnnotationMappingError(
            f"renderer identity for {semantic_label!r} at {prim_path!r} resolves to {len(ids)} instance IDs"
        )
    return instance == ids[0]


def _write_segmentation_audit(
    audit_dir: Path,
    scene_id: str,
    instance: np.ndarray,
    info: dict[str, Any],
    semantic_labels: dict[str, str],
    semantic_prim_paths: dict[str, str],
) -> dict[str, list[int]]:
    """Persist renderer identity evidence before accepting any tile label."""

    semantic_ids = _semantic_id_map(info, semantic_labels, semantic_prim_paths)
    audit_dir.mkdir(parents=True, exist_ok=True)
    (audit_dir / f"{scene_id}_instance_ids.json").write_text(
        json.dumps(
            {
                "semantic_labels": semantic_labels,
                "semantic_prim_paths": semantic_prim_paths,
                "matched_instance_ids": semantic_ids,
                "id_to_labels": info.get("idToLabels") or info.get("id_to_labels") or info.get("labels"),
            },
            indent=2,
            sort_keys=True,
            default=str,
        ),
        encoding="utf-8",
    )
    color = np.zeros((*instance.shape, 3), dtype=np.uint8)
    for identifier in np.unique(instance):
        identifier = int(identifier)
        if identifier == 0:
            continue
        color[instance == identifier] = (
            (identifier * 37) % 251 + 4,
            (identifier * 73) % 251 + 4,
            (identifier * 109) % 251 + 4,
        )
    Image.fromarray(color).save(audit_dir / f"{scene_id}_instance_ids.png")
    return semantic_ids


def _label_tile_instances(env) -> tuple[dict[str, str], dict[str, str]]:
    layout = env.scene_manager.layout_manager
    labels = (*_row_labels(), *DISCARD_LABELS)
    semantic = {label: f"vqa_make_kong_{label}" for label in labels}
    prim_paths = {}
    for label, semantic_label in semantic.items():
        entity = layout.get_scene_object(0, layout.get_instance_name(0, label))
        if entity is None:
            raise AnnotationMappingError(f"missing tile {label}")
        prim_paths[label] = _set_semantic_label(entity, semantic_label)
    return semantic, prim_paths


def _row_labels_left_to_right(env) -> list[str]:
    labels_with_x = []
    for label in _row_labels():
        _, position, _ = _label_object(env, label)
        labels_with_x.append((label, float(position[0])))
    return [label for label, _ in sorted(labels_with_x, key=lambda item: item[1])]


def _target_labels_for_discard(env, layout: dict[str, Any], discard_label: str) -> list[str]:
    """Return the three row tiles matching the discard's category, left-to-right."""

    records = {record["label"]: record for record in layout.get("Rigid", {}).get("mahjong", [])}
    category_idx = records[discard_label]["category_idx"]
    kong_labels = tuple(label for group in KONG_GROUPS for label in group)
    labels = [label for label in kong_labels if records[label]["category_idx"] == category_idx]
    if len(labels) != 3:
        raise RuntimeError(f"discard {discard_label} matches {len(labels)} kong tiles, expected exactly three")
    labels_with_x = []
    for label in labels:
        _, position, _ = _label_object(env, label)
        labels_with_x.append((label, float(position[0])))
    return [label for label, _ in sorted(labels_with_x, key=lambda item: item[1])]


def _fallen_tile_position(position: np.ndarray, direction: np.ndarray) -> np.ndarray:
    fallen_position = np.asarray(position, dtype=np.float32).copy()
    fallen_position += np.asarray(direction, dtype=np.float32) * FALLEN_FORWARD_OFFSET_M
    fallen_position[2] += FALLEN_Z_OFFSET_M
    return fallen_position


def _visibility_summary(statuses: list[str]) -> tuple[str, bool]:
    """Aggregate per-mask visibility into one record status."""

    if all(status == "visible" for status in statuses):
        return "visible", True
    if all(status in {"visible", "partially_visible"} for status in statuses):
        return "partially_visible", True
    return "partially_visible", False


def _render_scene(
    env,
    *,
    writer: SidecarWriter,
    image_dir: Path,
    audit_dir: Path,
    seed: int,
    variant: str,
    layout_id: int,
    layout: dict[str, Any],
    row_labels: list[str],
    target_labels: list[str],
    discard_label: str,
    group_index: int,
    fallen_case: FallenCase,
) -> None:
    target_set = set(target_labels)
    _, reference_position, _ = _label_object(env, discard_label)
    _set_label_pose(
        env,
        discard_label,
        _fallen_tile_position(reference_position, REFERENCE_TILE_PUSH_DIRECTION),
        REFERENCE_TILE_FALLEN_QUATERNION,
    )
    for label in fallen_case.fallen_labels:
        _, position, _ = _label_object(env, label)
        _set_label_pose(
            env,
            label,
            _fallen_tile_position(position, ROBOT_SIDE_PUSH_DIRECTION),
            ROBOT_SIDE_FALLEN_QUATERNION,
        )
    _restore_robot_home(env)
    _settle(env)

    scene_id = (
        f"make_kong_vqa_seed{seed}_variant{variant}_layout{layout_id:03d}_"
        f"group{group_index}_case{fallen_case.case_id}"
    )
    try:
        semantic_labels, semantic_prim_paths = _label_tile_instances(env)
        _reset_ego_render_product(env)
        rgb, _, instance, info = _capture_ego_annotations(env)
        semantic_ids = _write_segmentation_audit(
            audit_dir, scene_id, instance, info, semantic_labels, semantic_prim_paths
        )
        required_labels = set(row_labels) | {discard_label}
        invalid_mappings = {label: semantic_ids[label] for label in required_labels if len(semantic_ids[label]) != 1}
        if invalid_mappings:
            details = ", ".join(f"{label}={ids}" for label, ids in sorted(invalid_mappings.items()))
            raise AnnotationMappingError(f"semantic-to-instance mapping is not one-to-one: {details}")
        masks = {
            label: _mask_for_semantic(instance, info, semantic_labels[label], semantic_prim_paths[label])
            for label in required_labels
        }
    except AnnotationMappingError as error:
        writer.reject(
            base_record(
                sample_id=scene_id, task_name="make_kong", question_family="scene_validation", scene_id=scene_id
            ),
            str(error),
        )
        return
    image_name = f"{scene_id}.png"
    Image.fromarray(rgb).save(image_dir / image_name)
    image_reference = str(Path("images") / image_name)
    reference_status, reference_fraction, _ = classify_mask_visibility(masks[discard_label], TILE_VISIBILITY)

    def row_index(label: str) -> int:
        return row_labels.index(label) + 1

    def boxes_for(labels: list[str]) -> list[list[float]]:
        # bbox_from_mask yields xyxy; storage is yxyx ([y_min, x_min, y_max, x_max]).
        return [
            [box[1], box[0], box[3], box[2]]
            for label in labels
            if (box := bbox_from_mask(masks[label])) is not None
        ]

    def left_to_right_boxes(labels: list[str]) -> tuple[list[str], list[list[float]]]:
        # The prompt explicitly asks for "left-to-right order", which overrides
        # the contract's default top-left priority (docs/vqa/01).
        pairs = [(label, box) for label in labels if (box := bbox_from_mask(masks[label])) is not None]
        pairs.sort(key=lambda item: (item[1][1], item[1][0]))
        return (
            [label for label, _ in pairs],
            [[box[1], box[0], box[3], box[2]] for _, box in pairs],
        )

    def label_statuses(labels: list[str]) -> list[str]:
        return [classify_mask_visibility(masks[label], TILE_VISIBILITY)[0] for label in labels]

    def candidate(family: str, suffix: str, *, answer_type: str, prompt: str) -> dict[str, Any]:
        return base_record(
            sample_id=f"{scene_id}_{suffix}",
            task_name="make_kong",
            question_family=family,
            ego_image_reference=image_reference,
            image_width=int(rgb.shape[1]),
            image_height=int(rgb.shape[0]),
            prompt_text=prompt,
            answer_type=answer_type,
            world_state_valid=True,
            target_view="ego",
            source_layout=f"variant:{variant}/layout:{layout_id}",
            scene_id=scene_id,
        )

    def spatial_metadata(record: dict[str, Any], *, answerable: bool, statuses: list[str]) -> dict[str, Any]:
        status, supported = _visibility_summary(statuses + [reference_status])
        record["image_answerable"] = answerable and supported
        record["visibility_status"] = status
        record["visible_fraction"] = reference_fraction
        record["coordinate_space"] = "original_image_normalized_yxyx"
        record["bbox_definition"] = "visible_tight"
        return record

    audit_base = {
        "variant": variant,
        "layout_id": layout_id,
        "group_index": group_index,
        "discard_label": discard_label,
        "case_id": fallen_case.case_id,
        "correct_fallen_labels": list(fallen_case.correct_fallen),
        "wrong_fallen_labels": list(fallen_case.wrong_fallen),
        "fallen_labels": list(fallen_case.fallen_labels),
        "target_labels": list(target_labels),
        "reference_visible_fraction": reference_fraction,
        "reference_visibility_status": reference_status,
        "semantic_instance_ids": {label: semantic_ids[label][0] for label in sorted(required_labels)},
    }

    fallen_sorted = sorted(fallen_case.fallen_labels, key=row_index)
    missing_labels = [label for label in target_labels if label not in fallen_case.fallen_labels]
    wrong_sorted = [label for label in row_labels if label not in target_set and label in fallen_case.fallen_labels]

    writer.add(
        spatial_metadata(
            candidate(
                "fallen_tile_count",
                "fallen_tile_count",
                answer_type="integer",
                prompt="How many tiles on our side are currently knocked down? Answer with one integer.",
            )
            | {
                "answer_int": len(fallen_case.fallen_labels),
                "gt_source": "simulated_fallen_tile_set",
                "audit_metadata_json": json_dumps({**audit_base, "fallen_count": len(fallen_case.fallen_labels)}),
            },
            answerable=True,
            statuses=label_statuses(fallen_sorted),
        )
    )
    writer.add(
        spatial_metadata(
            candidate(
                "fallen_tile_indices",
                "fallen_tile_indices",
                answer_type="int_list",
                prompt=(
                    "Which tiles on our side are currently knocked down? Output their 1-based left-to-right "
                    "indices in ascending order, or 'none' if no tiles are down."
                ),
            )
            | {
                "answer_int_list": [row_index(label) for label in fallen_sorted],
                "gt_source": "simulated_fallen_tile_set",
                "audit_metadata_json": json_dumps(
                    {**audit_base, "fallen_indices": [row_index(label) for label in fallen_sorted]}
                ),
            },
            answerable=True,
            statuses=label_statuses(fallen_sorted),
        )
    )
    missing_boxes = boxes_for(missing_labels)
    missing_sorted, missing_sorted_boxes = left_to_right_boxes(missing_labels)
    writer.add(
        spatial_metadata(
            candidate(
                "missing_matching_tile_bboxes",
                "missing_matching_tile_bboxes",
                answer_type="bbox_list",
                prompt=(
                    "Which of the three tiles matching the suit of the tile knocked down by the opponent are "
                    "still standing? Output one bounding box per tile in left-to-right order, or 'none' if all "
                    "three are down."
                ),
            )
            | {
                "answer_bbox_list_yxyx_norm": missing_sorted_boxes,
                "gt_source": "simulated_matching_tile_identity_and_pose",
                "audit_metadata_json": json_dumps(
                    {**audit_base, "missing_labels": missing_sorted, "missing_bboxes": missing_sorted_boxes}
                ),
            },
            answerable=all(box is not None for box in missing_boxes),
            statuses=label_statuses(missing_labels),
        )
    )
    wrong_boxes = boxes_for(wrong_sorted)
    wrong_sorted, wrong_sorted_boxes = left_to_right_boxes(wrong_sorted)
    writer.add(
        spatial_metadata(
            candidate(
                "wrong_fallen_tile_bboxes",
                "wrong_fallen_tile_bboxes",
                answer_type="bbox_list",
                prompt=(
                    "Which tiles on our side whose suit does not match the opponent's tile were incorrectly "
                    "knocked down? Output one bounding box per tile in left-to-right order, or 'none' if none."
                ),
            )
            | {
                "answer_bbox_list_yxyx_norm": wrong_sorted_boxes,
                "gt_source": "simulated_tile_identity_and_pose",
                "audit_metadata_json": json_dumps(
                    {**audit_base, "wrong_labels": wrong_sorted, "wrong_bboxes": wrong_sorted_boxes}
                ),
            },
            answerable=all(box is not None for box in wrong_boxes),
            statuses=label_statuses(wrong_sorted),
        )
    )
    if fallen_case.case_id == "f0":
        mahjong_records = layout.get("Rigid", {}).get("mahjong", [])
        category_idx = next(record["category_idx"] for record in mahjong_records if record["label"] == discard_label)
        suit = face_of_category(category_idx)
        writer.add(
            spatial_metadata(
                candidate(
                    "discard_suit",
                    "discard_suit",
                    answer_type="short_text",
                    prompt=(
                        "What is the suit of the tile knocked down by the opponent robot arm? "
                        f"Answer with one of: {', '.join(FACE_NAMES)}."
                    ),
                )
                | {
                    "answer_text": suit,
                    "gt_source": "simulated_discard_tile_face",
                    "audit_metadata_json": json_dumps({**audit_base, "discard_suit": suit}),
                },
                answerable=True,
                statuses=[],
            )
        )


def main() -> None:
    _configure_logging()
    variants = [item.strip().lower() for item in ARGS.variant.split(",") if item.strip()]
    invalid_variants = [variant for variant in variants if variant not in VARIANTS]
    if invalid_variants:
        raise ValueError(f"--variant contains invalid values {invalid_variants}; expected values in {list(VARIANTS)}.")
    target_groups = _parse_int_csv(ARGS.target_groups, valid={0, 1, 2, 3}, flag="--target-groups")
    if ARGS.fps <= 0:
        raise ValueError("--fps must be positive.")
    writer = SidecarWriter(ARGS.output_dir, overwrite=ARGS.overwrite)
    image_dir = writer.prepare_images_dir()
    audit_dir = writer.prepare_audit_dir()

    env = None
    try:
        config = _build_env_config(ARGS.device_id, ARGS.seed)
        planner_flags = [(cfg.get("robot_name"), cfg.get("need_planner")) for cfg in config.robot.robots]
        LOGGER.info("planner flags=%s", planner_flags)
        pool = load_vqa_layout_pool(ARGS.layout_root, variants=variants)
        layout_ids = _parse_layout_ids(ARGS.layout_ids, pool)
        LOGGER.info(
            "seed=%s variants=%s layouts=%s groups=%s output=%s",
            ARGS.seed,
            variants,
            layout_ids,
            target_groups,
            ARGS.output_dir,
        )
        coverage: dict[str, dict[str, Any]] = {}
        for layout_id in layout_ids:
            for variant in variants:
                scene_layout = pool[(variant, layout_id)][1]
                env = _create_env(deepcopy(config))
                try:
                    LOGGER.info("creating and resetting variant=%s layout=%s", variant, layout_id)
                    _reset_layout(env, layout_id, scene_layout)
                    base_poses = _snapshot_tile_poses(env)
                    row_labels = _row_labels_left_to_right(env)
                    for group_index in target_groups:
                        discard_label = DISCARD_LABELS[group_index]
                        target_labels = _target_labels_for_discard(env, scene_layout, discard_label)
                        rng = random.Random(
                            ARGS.seed * 1000003 + layout_id * 65537 + group_index * 1009 + variants.index(variant)
                        )
                        cases, skipped = plan_cases(row_labels, target_labels, variant, rng)
                        coverage.setdefault(f"variant_{variant}_layout{layout_id}", {})[f"group{group_index}"] = {
                            "discard_label": discard_label,
                            "case_ids": [case.case_id for case in cases],
                            "skipped": skipped,
                            "target_labels": target_labels,
                        }
                        for fallen_case in cases:
                            _restore_tile_poses(env, base_poses)
                            LOGGER.info(
                                "capturing variant=%s layout=%s group=%s case=%s",
                                variant,
                                layout_id,
                                group_index,
                                fallen_case.case_id,
                            )
                            _render_scene(
                                env,
                                writer=writer,
                                image_dir=image_dir,
                                audit_dir=audit_dir,
                                seed=ARGS.seed,
                                variant=variant,
                                layout_id=layout_id,
                                layout=scene_layout,
                                row_labels=row_labels,
                                target_labels=target_labels,
                                discard_label=discard_label,
                                group_index=group_index,
                                fallen_case=fallen_case,
                            )
                finally:
                    env.close()
                    env = None

        report = writer.write(
            {
                "collector": "vqa_gen/make_kong/generate_make_kong_vqa.py",
                "task_name": "make_kong",
                "source_action_dataset": "RoboDojo_ee_lerobot_v30_video",
                "seed": ARGS.seed,
                "variants": variants,
                "layout_ids": layout_ids,
                "max_layouts": ARGS.max_layouts,
                "target_groups": target_groups,
                "layout_root": str(ARGS.layout_root),
                "face_vocabulary": list(FACE_NAMES),
                "coverage": coverage,
                "camera": "cam_head",
                "fps": ARGS.fps,
                "row_tiles": len(_row_labels()),
                "fallen_forward_offset_m": FALLEN_FORWARD_OFFSET_M,
                "fallen_z_offset_m": FALLEN_Z_OFFSET_M,
                "render": {
                    "antialiasing_mode": "DLAA",
                    "stabilization_frames": RENDER_STABILIZATION_FRAMES,
                    "ego_render_product_recreated_per_snapshot": True,
                },
                "command": " ".join(sys.argv),
            }
        )
        LOGGER.info("wrote %s accepted records to %s", report["accepted_records"], ARGS.output_dir)
    except Exception as error:
        LOGGER.exception("generation failed: %s", error)
        raise
    finally:
        if env is not None:
            env.close()
        simulation_app.close()


if __name__ == "__main__":
    main()
